name = "lwp-analytics"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "lwp_analytics"
database_name = "lwp-analytics"
database_id = "c3633feb-70a4-4827-80d2-b14ebf84e3dd"

